name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  go-ci:
    uses: DecisiveAI/ci/.github/workflows/go-ci.yml@f2e1e3d
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      PLATFORM_HEALTH_ACCESS_APP_ID: ${{ vars.PLATFORM_HEALTH_ACCESS_APP_ID }}