name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-ci:
    uses: DecisiveAI/ci/.github/workflows/go-ci.yml@dj/ENG-595-housekeeping-fix-code-coverage-comments-collection
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      PLATFORM_HEALTH_ACCESS_APP_ID: ${{ vars.PLATFORM_HEALTH_ACCESS_APP_ID }}